import type {
  Achievement,
  Application,
  Comment,
  Conversation,
  Experience,
  MediaItem,
  Message,
  Notification,
  Opportunity,
  Post,
  Profile,
  Report,
  Sport,
  StatEntry,
} from "@/lib/types";

export const sports: Sport[] = [
  { id: "sport-football", slug: "football", name_fr: "Football", name_en: "Football", icon: "⚽" },
  { id: "sport-basketball", slug: "basketball", name_fr: "Basketball", name_en: "Basketball", icon: "🏀" },
  { id: "sport-tennis", slug: "tennis", name_fr: "Tennis", name_en: "Tennis", icon: "🎾" },
  { id: "sport-rugby", slug: "rugby", name_fr: "Rugby", name_en: "Rugby", icon: "🏉" },
  { id: "sport-athletics", slug: "athletics", name_fr: "Athlétisme", name_en: "Athletics", icon: "🏃" },
  { id: "sport-swimming", slug: "swimming", name_fr: "Natation", name_en: "Swimming", icon: "🏊" },
  { id: "sport-volleyball", slug: "volleyball", name_fr: "Volleyball", name_en: "Volleyball", icon: "🏐" },
  { id: "sport-handball", slug: "handball", name_fr: "Handball", name_en: "Handball", icon: "🤾" },
];

export const footballPositions = [
  { slug: "gk", name_fr: "Gardien", name_en: "Goalkeeper" },
  { slug: "cb", name_fr: "Défenseur central", name_en: "Center Back" },
  { slug: "lb", name_fr: "Latéral gauche", name_en: "Left Back" },
  { slug: "rb", name_fr: "Latéral droit", name_en: "Right Back" },
  { slug: "cdm", name_fr: "Milieu défensif", name_en: "Defensive Midfielder" },
  { slug: "cm", name_fr: "Milieu central", name_en: "Central Midfielder" },
  { slug: "cam", name_fr: "Milieu offensif", name_en: "Attacking Midfielder" },
  { slug: "lw", name_fr: "Ailier gauche", name_en: "Left Winger" },
  { slug: "rw", name_fr: "Ailier droit", name_en: "Right Winger" },
  { slug: "st", name_fr: "Attaquant", name_en: "Striker" },
];

export const footballLevels = [
  { slug: "youth", name_fr: "Jeunes / Académie", name_en: "Youth / Academy" },
  { slug: "amateur", name_fr: "Amateur", name_en: "Amateur" },
  { slug: "regional", name_fr: "Régional", name_en: "Regional" },
  { slug: "national", name_fr: "National", name_en: "National" },
  { slug: "semi-pro", name_fr: "Semi-pro", name_en: "Semi-pro" },
  { slug: "pro", name_fr: "Professionnel", name_en: "Professional" },
];

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600000).toISOString();

export const demoProfiles: Profile[] = [
  {
    id: "user-athlete-1",
    email: "amine@playce.demo",
    handle: "amine.benali",
    full_name: "Amine Benali",
    role: "athlete",
    avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Amine",
    cover_url: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&q=80",
    bio: "Attaquant polyvalent, rapide et décisif. Ouvert aux opportunités en Europe.",
    city: "Lyon",
    country: "France",
    birth_date: "2002-05-14",
    hide_age: false,
    sport_id: "sport-football",
    sport: sports[0],
    position: "st",
    level: "semi-pro",
    dominant_side: "right",
    availability: "open",
    languages: ["fr", "en", "ar"],
    goals: "Rejoindre un club professionnel et progresser chaque saison.",
    current_club: "Olympique Régional Lyon",
    visibility: "public",
    allow_direct_contact: true,
    email_verified: true,
    identity_verified: true,
    completeness: 100,
    is_suspended: false,
    created_at: daysAgo(40),
    updated_at: daysAgo(1),
  },
  {
    id: "user-athlete-2",
    email: "sofia@playce.demo",
    handle: "sofia.martinez",
    full_name: "Sofia Martinez",
    role: "athlete",
    avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia",
    cover_url: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&q=80",
    bio: "Milieu offensif créative. Expérience en D2 féminine.",
    city: "Barcelona",
    country: "Spain",
    birth_date: "2001-11-02",
    hide_age: false,
    sport_id: "sport-football",
    sport: sports[0],
    position: "cam",
    level: "national",
    dominant_side: "left",
    availability: "looking",
    languages: ["es", "en", "fr"],
    goals: "Trouver un club ambitieux pour la saison prochaine.",
    current_club: "FC Barcelone Femení B",
    visibility: "public",
    allow_direct_contact: true,
    email_verified: true,
    identity_verified: false,
    completeness: 90,
    is_suspended: false,
    created_at: daysAgo(25),
    updated_at: daysAgo(2),
  },
  {
    id: "user-club-1",
    email: "recrutement@asc.demo",
    handle: "asc-metz",
    full_name: "ASC Metz Academy",
    role: "club",
    avatar_url: "https://api.dicebear.com/9.x/identicon/svg?seed=ASCMetz",
    cover_url: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=1200&q=80",
    bio: "Académie de football formant les talents de demain. Ouverte aux profils U17–U21.",
    city: "Metz",
    country: "France",
    sport_id: "sport-football",
    sport: sports[0],
    level: "national",
    availability: "open",
    languages: ["fr", "en"],
    goals: "Identifier et former des talents omnisports.",
    visibility: "public",
    allow_direct_contact: true,
    email_verified: true,
    identity_verified: true,
    completeness: 85,
    is_suspended: false,
    created_at: daysAgo(60),
    updated_at: daysAgo(3),
  },
  {
    id: "user-scout-1",
    email: "marc@scout.demo",
    handle: "marc.dubois",
    full_name: "Marc Dubois",
    role: "scout",
    avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Marc",
    bio: "Scout indépendant, spécialisé football et basketball Europe.",
    city: "Paris",
    country: "France",
    sport_id: "sport-football",
    sport: sports[0],
    availability: "open",
    languages: ["fr", "en"],
    visibility: "public",
    allow_direct_contact: true,
    email_verified: true,
    identity_verified: true,
    completeness: 70,
    is_suspended: false,
    created_at: daysAgo(50),
    updated_at: daysAgo(5),
  },
  {
    id: "user-coach-1",
    email: "lea@coach.demo",
    handle: "lea.nguyen",
    full_name: "Léa Nguyen",
    role: "coach",
    avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lea",
    bio: "Coach UEFA B, préparation physique et technique.",
    city: "Marseille",
    country: "France",
    sport_id: "sport-football",
    sport: sports[0],
    level: "national",
    availability: "looking",
    languages: ["fr", "en", "vi"],
    visibility: "public",
    allow_direct_contact: true,
    email_verified: true,
    identity_verified: false,
    completeness: 75,
    is_suspended: false,
    created_at: daysAgo(30),
    updated_at: daysAgo(4),
  },
  {
    id: "user-admin-1",
    email: "admin@playce.demo",
    handle: "playce.admin",
    full_name: "PLAYCE Admin",
    role: "admin",
    avatar_url: "https://api.dicebear.com/9.x/shapes/svg?seed=Admin",
    bio: "Administrateur plateforme.",
    city: "Paris",
    country: "France",
    availability: "unavailable",
    languages: ["fr", "en"],
    visibility: "limited",
    allow_direct_contact: false,
    email_verified: true,
    identity_verified: true,
    completeness: 100,
    is_suspended: false,
    created_at: daysAgo(100),
    updated_at: daysAgo(0),
  },
  {
    id: "user-athlete-3",
    email: "kevin@playce.demo",
    handle: "kevin.okafor",
    full_name: "Kevin Okafor",
    role: "athlete",
    avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=Kevin",
    bio: "Défenseur central athlétique, 1m88. Cherche club en Ligue 2 / National.",
    city: "Lille",
    country: "France",
    birth_date: "2000-08-21",
    sport_id: "sport-football",
    sport: sports[0],
    position: "cb",
    level: "national",
    dominant_side: "right",
    availability: "open",
    languages: ["fr", "en"],
    current_club: "USL Dunkerque B",
    visibility: "public",
    allow_direct_contact: true,
    email_verified: true,
    identity_verified: false,
    completeness: 80,
    is_suspended: false,
    created_at: daysAgo(15),
    updated_at: daysAgo(1),
  },
];

export const demoExperiences: Experience[] = [
  {
    id: "exp-1",
    profile_id: "user-athlete-1",
    organization: "Olympique Régional Lyon",
    role: "Attaquant",
    level: "semi-pro",
    start_date: "2023-07-01",
    is_current: true,
    description: "12 buts en 22 matchs cette saison.",
  },
  {
    id: "exp-2",
    profile_id: "user-athlete-1",
    organization: "AS Villeurbanne U19",
    role: "Attaquant",
    level: "youth",
    start_date: "2020-09-01",
    end_date: "2023-06-30",
    description: "Champion régional U19.",
  },
  {
    id: "exp-3",
    profile_id: "user-athlete-2",
    organization: "FC Barcelone Femení B",
    role: "Milieu offensif",
    level: "national",
    start_date: "2022-01-01",
    is_current: true,
  },
];

export const demoStats: StatEntry[] = [
  { id: "stat-1", profile_id: "user-athlete-1", label: "Buts", value: "12", season: "2025/26", is_declarative: true, source: "Club" },
  { id: "stat-2", profile_id: "user-athlete-1", label: "Passes décisives", value: "7", season: "2025/26", is_declarative: true },
  { id: "stat-3", profile_id: "user-athlete-1", label: "Matchs", value: "22", season: "2025/26", is_declarative: true },
  { id: "stat-4", profile_id: "user-athlete-1", label: "Minutes", value: "1840", season: "2025/26", is_declarative: true },
  { id: "stat-5", profile_id: "user-athlete-2", label: "Buts", value: "5", season: "2025/26", is_declarative: true },
  { id: "stat-6", profile_id: "user-athlete-2", label: "Passes décisives", value: "11", season: "2025/26", is_declarative: true },
  { id: "stat-7", profile_id: "user-athlete-3", label: "Tacles réussis", value: "68", season: "2025/26", is_declarative: true },
  { id: "stat-8", profile_id: "user-athlete-3", label: "Duels aériens %", value: "74", season: "2025/26", is_declarative: true },
];

export const demoMedia: MediaItem[] = [
  {
    id: "media-1",
    profile_id: "user-athlete-1",
    type: "video",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnail_url: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&q=80",
    title: "Highlights 2025/26",
    is_highlight: true,
  },
  {
    id: "media-2",
    profile_id: "user-athlete-1",
    type: "photo",
    url: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    title: "Match day",
    is_highlight: false,
  },
];

export const demoAchievements: Achievement[] = [
  { id: "ach-1", profile_id: "user-athlete-1", title: "Champion Régional U19", year: "2023", type: "title" },
  { id: "ach-2", profile_id: "user-athlete-1", title: "Licence FFF", year: "2024", type: "license", issuer: "FFF" },
  { id: "ach-3", profile_id: "user-coach-1", title: "UEFA B", year: "2022", type: "diploma", issuer: "UEFA" },
];

export const demoPosts: Post[] = [
  {
    id: "post-1",
    author_id: "user-athlete-1",
    author: demoProfiles[0],
    type: "highlight",
    content: "Doublé aujourd'hui ! Toujours plus haut. #football #goals",
    media_url: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    hashtags: ["football", "goals"],
    likes_count: 48,
    comments_count: 6,
    saves_count: 12,
    liked_by_me: false,
    created_at: hoursAgo(3),
  },
  {
    id: "post-2",
    author_id: "user-club-1",
    author: demoProfiles[2],
    type: "announcement",
    content: "Nous recherchons un ailier U19 pour la saison. Postulez via PLAYCE ! ⚽",
    hashtags: ["recrutement", "football", "academy"],
    likes_count: 32,
    comments_count: 4,
    saves_count: 18,
    created_at: hoursAgo(8),
  },
  {
    id: "post-3",
    author_id: "user-athlete-2",
    author: demoProfiles[1],
    type: "training",
    content: "Session technique du jour. La créativité se travaille. #training",
    media_url: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    hashtags: ["training", "football"],
    likes_count: 67,
    comments_count: 9,
    saves_count: 5,
    created_at: hoursAgo(14),
  },
  {
    id: "post-4",
    author_id: "user-scout-1",
    author: demoProfiles[3],
    type: "text",
    content: "Belle génération de défenseurs en France cette année. Le talent est partout.",
    hashtags: ["scouting", "football"],
    likes_count: 21,
    comments_count: 3,
    saves_count: 8,
    created_at: daysAgo(1),
  },
  {
    id: "post-5",
    author_id: "user-athlete-3",
    author: demoProfiles[6],
    type: "reel",
    content: "Défense solide, concentration maximale. #reel #cb",
    media_url: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    thumbnail_url: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    hashtags: ["reel", "cb", "football"],
    likes_count: 89,
    comments_count: 11,
    saves_count: 22,
    created_at: hoursAgo(5),
  },
  {
    id: "post-6",
    author_id: "user-athlete-1",
    author: demoProfiles[0],
    type: "reel",
    content: "Finition clinique en 1 contre 1. BE SEEN. #highlight",
    media_url: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    thumbnail_url: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    hashtags: ["highlight", "striker"],
    likes_count: 156,
    comments_count: 24,
    saves_count: 41,
    created_at: hoursAgo(20),
  },
];

export const demoComments: Comment[] = [
  {
    id: "c-1",
    post_id: "post-1",
    author_id: "user-scout-1",
    author: demoProfiles[3],
    content: "Belle performance Amine, continue !",
    created_at: hoursAgo(2),
  },
  {
    id: "c-2",
    post_id: "post-1",
    author_id: "user-club-1",
    author: demoProfiles[2],
    content: "Profil intéressant. On suit.",
    created_at: hoursAgo(1),
  },
];

export const demoOpportunities: Opportunity[] = [
  {
    id: "opp-1",
    author_id: "user-club-1",
    author: demoProfiles[2],
    type: "offer",
    title: "Ailier U19 – ASC Metz Academy",
    organization: "ASC Metz Academy",
    sport_id: "sport-football",
    sport: sports[0],
    position: "rw",
    level: "youth",
    city: "Metz",
    country: "France",
    contract_type: "Formation",
    compensation: "Indemnités + hébergement",
    deadline: "2026-09-30",
    description: "Nous recherchons un ailier droit rapide et technique pour intégrer notre centre de formation U19.",
    criteria: "Né entre 2007 et 2009, permis de travailler en France, niveau régional minimum.",
    status: "open",
    applications_count: 8,
    match_score: 72,
    match_reasons: ["sport", "level", "location"],
    created_at: daysAgo(2),
  },
  {
    id: "opp-2",
    author_id: "user-club-1",
    author: demoProfiles[2],
    type: "offer",
    title: "Attaquant semi-pro – saison 2026/27",
    organization: "ASC Metz Academy",
    sport_id: "sport-football",
    sport: sports[0],
    position: "st",
    level: "semi-pro",
    city: "Metz",
    country: "France",
    contract_type: "CDD saisonnier",
    compensation: "À négocier",
    deadline: "2026-08-31",
    description: "Poste d'attaquant disponible. Profil décisif, travailleur et disponible immédiatement.",
    criteria: "Expérience senior, statistiques vérifiables, mobilité géographique.",
    status: "open",
    applications_count: 14,
    match_score: 95,
    match_reasons: ["sport", "position", "level", "availability"],
    created_at: daysAgo(1),
  },
  {
    id: "opp-3",
    author_id: "user-athlete-2",
    author: demoProfiles[1],
    type: "demand",
    title: "Recherche club – Milieu offensif féminin",
    organization: null,
    sport_id: "sport-football",
    sport: sports[0],
    position: "cam",
    level: "national",
    city: "Barcelona",
    country: "Spain",
    contract_type: "Professionnel",
    description: "Milieu créative disponible pour la prochaine saison. Ouverte à l'Europe.",
    status: "open",
    applications_count: 3,
    created_at: daysAgo(3),
  },
  {
    id: "opp-4",
    author_id: "user-scout-1",
    author: demoProfiles[3],
    type: "offer",
    title: "Défenseur central National / Ligue 2",
    organization: "Réseau Marc Dubois",
    sport_id: "sport-football",
    sport: sports[0],
    position: "cb",
    level: "national",
    city: "France",
    country: "France",
    contract_type: "Professionnel",
    description: "Plusieurs clubs cherchent un CB athlétique pour renforcer leur défense.",
    status: "open",
    applications_count: 6,
    match_score: 88,
    match_reasons: ["sport", "position", "level", "location"],
    created_at: hoursAgo(10),
  },
];

export const demoApplications: Application[] = [
  {
    id: "app-1",
    opportunity_id: "opp-2",
    opportunity: demoOpportunities[1],
    applicant_id: "user-athlete-1",
    applicant: demoProfiles[0],
    message: "Bonjour, mon profil correspond parfaitement. Sports ID joint.",
    status: "viewed",
    created_at: hoursAgo(6),
    updated_at: hoursAgo(2),
  },
  {
    id: "app-2",
    opportunity_id: "opp-4",
    opportunity: demoOpportunities[3],
    applicant_id: "user-athlete-3",
    applicant: demoProfiles[6],
    message: "Défenseur disponible immédiatement.",
    status: "shortlisted",
    created_at: hoursAgo(8),
    updated_at: hoursAgo(1),
  },
];

export const demoMessages: Message[] = [
  {
    id: "msg-1",
    conversation_id: "conv-1",
    sender_id: "user-club-1",
    sender: demoProfiles[2],
    content: "Bonjour Amine, nous avons consulté votre candidature. Disponibles pour un essai ?",
    type: "text",
    created_at: hoursAgo(2),
  },
  {
    id: "msg-2",
    conversation_id: "conv-1",
    sender_id: "user-athlete-1",
    sender: demoProfiles[0],
    content: "Bonjour ! Oui, avec plaisir. Quelles dates avez-vous en tête ?",
    type: "text",
    created_at: hoursAgo(1),
  },
  {
    id: "msg-3",
    conversation_id: "conv-2",
    sender_id: "user-scout-1",
    sender: demoProfiles[3],
    content: "Kevin, ton profil m'intéresse pour un club en National.",
    type: "text",
    created_at: hoursAgo(4),
  },
];

export const demoConversations: Conversation[] = [
  {
    id: "conv-1",
    participant_ids: ["user-athlete-1", "user-club-1"],
    participants: [demoProfiles[0], demoProfiles[2]],
    last_message: demoMessages[1],
    updated_at: hoursAgo(1),
    unread_count: 0,
  },
  {
    id: "conv-2",
    participant_ids: ["user-athlete-3", "user-scout-1"],
    participants: [demoProfiles[6], demoProfiles[3]],
    last_message: demoMessages[2],
    updated_at: hoursAgo(4),
    unread_count: 1,
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notif-1",
    user_id: "user-athlete-1",
    type: "application",
    title: "Candidature consultée",
    body: "ASC Metz Academy a consulté votre candidature.",
    link: "/opportunities/opp-2",
    read: false,
    created_at: hoursAgo(2),
  },
  {
    id: "notif-2",
    user_id: "user-athlete-1",
    type: "message",
    title: "Nouveau message",
    body: "ASC Metz Academy vous a envoyé un message.",
    link: "/messages/conv-1",
    read: false,
    created_at: hoursAgo(2),
  },
  {
    id: "notif-3",
    user_id: "user-athlete-1",
    type: "like",
    title: "Nouveau like",
    body: "Marc Dubois a aimé votre publication.",
    link: "/feed",
    read: true,
    created_at: hoursAgo(5),
  },
  {
    id: "notif-4",
    user_id: "user-club-1",
    type: "application",
    title: "Nouvelle candidature",
    body: "Amine Benali a candidaté à votre offre.",
    link: "/opportunities/opp-2",
    read: false,
    created_at: hoursAgo(6),
  },
];

export const demoReports: Report[] = [
  {
    id: "rep-1",
    reporter_id: "user-athlete-2",
    target_type: "post",
    target_id: "post-4",
    reason: "spam",
    details: "Contenu promotionnel non pertinent",
    status: "pending",
    created_at: daysAgo(1),
  },
];

export const CURRENT_DEMO_USER_ID = "user-athlete-1";

export function getDemoUser(id = CURRENT_DEMO_USER_ID) {
  return demoProfiles.find((p) => p.id === id) ?? demoProfiles[0];
}
